### ISSUE TITLE
Theme Switching doesnt work on web?

### ISSUE THREAD

**Issue by geektutor** [kherel/animated_theme_switcher#13]
Hi,

I was trying to use this with Flutter web and I got this error

`Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/scene_builder.dart:95:16
matrix4[0] == window.devicePixelRatio &&
           matrix4[5] == window.devicePixelRatio
is not true
`

How do i fix it?

**Comment by MahdiPishguy** [comment]
@geektutor  this library is not provided for web yet

**Comment by geektutor** [comment]
Thank you. Figured out a hack

**Comment by shinewanna** [comment]
need web support
