### ISSUE TITLE
where locations show be used ThemeSwitchingArea

### ISSUE THREAD

**Issue by MahdiPishguy** [kherel/animated_theme_switcher#20]
we must use `ThemeSwitchingArea` in every screens which they are contained `Scaffold()` ?

**Comment by Viper-Bit** [comment]
no you must use ThemeSwitchingArea just in pages/screens that u want use ThemeSwitcher, in other word in any page that u want use animation

**Comment by MahdiPishguy** [comment]
@Viper-Bit so, changing animation work in all of screens even we don't have `ThemeSwitchingArea`?

**Comment by kherel** [comment]
@MahdiPishguy 
No. Let say you have several screens, and one of them is Settings Screen. This screen is the only screen where you can change your theme, the only screen where you need animation. In this example need to use ThemeSwitchingArea only at the Settings Screen.

Another example. You have several screen, and you put button to chane theme inside a Drawer widget. So you can change theme on any screen. Than you need to use a ThemeSwitchingArea widget on every screen of your app.
