### ISSUE TITLE
i want to set default theme when the user sing in for the first time in app ,without selected a button or a checkbox 

### ISSUE THREAD

**Issue by SediqeZangane** [kherel/animated_theme_switcher#21]
i want to set it in mySplashScreen
but i donot kwnow where should i put this:
    ThemeSwitcher.of(context).changeTheme(
      theme: myTheme,
    );

 my Code:

import 'package:animated_theme_switcher/animated_theme_switcher.dart';
import 'package:flutter/material.dart';
import 'package:background_fetch/background_fetch.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

import '../pages/home_page.dart';
import '../pages/signin_screen.dart';
import '../pages/stepup_page.dart';
import '../flavors.dart';
import '../style/style.dart';
import '../helper/helper.dart';
import '../models/localappconfig.dart';
import '../sqliteProvider/userappconfig_provider.dart';
import '../ui/loading.dart';
import '../utils/gradientutil.dart';
import '../utils/uidata.dart';
import '../helper/dbhelper.dart';
import '../sqliteProvider/localappconfig_provider.dart';
import '../models/UserAppConfig.dart';

class SplashScreen extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => new SplashScreenState();
}

class SplashScreenState extends State<SplashScreen> {
  ThemeData myTheme;

  @override
  void initState() {
    super.initState();
    checkLogin();
    initPlatformState();
    Helper.notificationPermission();
    // _configureSelectNotificationSubject();
  }

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    setInitTheme();
  }
  // void _configureSelectNotificationSubject() {
  //   final selectNotification = BehaviorSubject<String>();

  //   selectNotification.stream.listen((String payload) async {
  //     await Navigator.push(
  //       context,
  //       MaterialPageRoute(builder: (context) => WarePage()),
  //     );
  //   });
  // }

  @override
  Widget build(BuildContext context) {
    ScreenUtil.init(context, width: 750, height: 1334, allowFontScaling: true);

    return ThemeSwitchingArea(
      child: Scaffold(
          body: Container(
        height: double.infinity,
        width: double.infinity,
        decoration: BoxDecoration(
          gradient: PAGE_BACKGROUND,
        ),
        child: new Stack(
          fit: StackFit.expand,
          children: <Widget>[
            new Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                new Container(
                  width: 400.w,
                  height: 400.h,
                  decoration: new BoxDecoration(
                      image: new DecorationImage(
                          image: new AssetImage(UIData.imageSorooshan),
                          fit: BoxFit.fill)),
                ),
                new Text(F.companyInfo.appCompanyName,
                    style: Style.styleTextBlack(TEXT_SIZE_50, FontWeight.w700))
              ],
            ),
            new Padding(
              padding: const EdgeInsets.only(bottom: 30),
              child: new Align(
                alignment: Alignment.bottomCenter,
                child: LoadingSpinner(Theme.of(context).primaryColor),
              ),
            ),
          ],
        ),
      )),
    );
  }

  Future<void> checkLogin() async {
    DbHelper dbHelper = new DbHelper();
    var count = await dbHelper.getCount('LocalAppConfig');
    if (count == null || (count != null && count == 0)) {
      //set Default LocalAppConfig
      LocalAppConfigProvider configProvider = new LocalAppConfigProvider();
      LocalAppConfig config =
          new LocalAppConfig(1, 0, 0.0, DateTime.now().toString());
      await configProvider.insert(config);
      //set Default UserAppConfig
      UserAppConfig appConfig = new UserAppConfig(
        sql_Apc_Id: 1,
        token: "",
        isOnlineDateTime: DateTime.now().toString(),
        logOut: 1,
        setUp: 0,
        // primarycolor: "4294924066",
        // accentcolor: "4294924066",
        // fontsize: 22.0
      );
      UserAppConfigProvider userAppConfigProvider = new UserAppConfigProvider();
      await userAppConfigProvider.insert(appConfig);
      Helper.navigationReplace(context, SignInScreen());
    } else if (count != null && count > 0) {
      var mapuser = await dbHelper.getItem('UserAppConfig');
      if (mapuser != null) {
        UserAppConfig appConfig = new UserAppConfig.fromMapDb(mapuser);
        if (appConfig != null && appConfig.logOut == 0) {
          if (appConfig.setUp == 0)
            Helper.navigationReplace(context, SetUpPage());
          else
            Helper.navigationReplace(context, HomePage());
        } else
          Helper.navigationReplace(context, SignInScreen());
      } else
        Helper.navigationReplace(context, SignInScreen());
    }
  }

  Future<void> initPlatformState() async {
    // Configure BackgroundFetch.
    BackgroundFetch.configure(
            BackgroundFetchConfig(
                minimumFetchInterval: 30,
                stopOnTerminate: false,
                startOnBoot: true,
                enableHeadless: true,
                requiresBatteryNotLow: false,
                requiresCharging: false,
                requiresStorageNotLow: false,
                requiresDeviceIdle: false,
                requiredNetworkType: NetworkType.ANY),
            _onBackgroundFetch)
        .then((int status) async {
      print('[BackgroundFetch] configure success: $status');
      await Helper.backServiceReception();
    }).catchError((e) {
      print('[BackgroundFetch] configure ERROR: $e');
    });

    if (!mounted) return;
  }

  void _onBackgroundFetch(String taskId) async {
    await Helper.backServiceReception();
    // IMPORTANT:  You must signal completion of your fetch task or the OS can punish your app
    // for taking too long in the background.
    BackgroundFetch.finish(taskId);
  }

  void setInitTheme() async {
    UserAppConfigProvider _userAppConfigProvider = UserAppConfigProvider();
    await _userAppConfigProvider.getUserAppConfig().then((_userAppConfig) {
      if (_userAppConfig != null && _userAppConfig.sql_Apc_Id > 0) {
        myTheme = ThemeData(
          // appBarTheme: ThemeData.light().appBarTheme.copyWith(color: Colors.deepOrange),
          brightness: Brightness.light,
          fontFamily: UIData.vazirFont,
          // primaryColor: Color(int.parse(_userAppConfig.primarycolor)),
          // accentColor: Color(int.parse(_userAppConfig.accentcolor)),
          primaryColor: Colors.deepOrange,
          accentColor: Colors.deepOrange,
          // primaryTextTheme:
          //     TextTheme(bodyText1: TextStyle(fontSize: _userAppConfig.fontsize)),

          // canvasColor: kLightPrimaryColor,
          // backgroundColor: accentcolor,
          // iconTheme: ThemeData.light().iconTheme.copyWith(
          //       color: Color(0xFF373737),
          //     ),
          // textTheme: ThemeData.light().textTheme.apply(
          //       fontFamily: UIData.vazirFont,
          //       bodyColor: Color(0xFF373737),
          //       displayColor: Color(0xFF373737),
          //     ),
        );
      }
    });
    ThemeSwitcher.of(context).changeTheme(
      theme: myTheme,
    );
  }
}

**Comment by Viper-Bit** [comment]
If you have a switch in your splash screen for changing theme then you must use ThemeSwitcher.of(context).changeTheme in onTap event of that switch، check example for more detail.

**Comment by SediqeZangane** [comment]
hi :) 
i solved my problem,we should put our theme before   runApp(new MyApp());
                                               like this:
void main() {
    ThemeData myTheme;
    UserAppConfigProvider _userAppConfigProvider = UserAppConfigProvider();
    await _userAppConfigProvider.getUserAppConfig().then((_userAppConfig) {
      if (_userAppConfig != null && _userAppConfig.sql_Apc_Id > 0) {
        myTheme = ThemeData(
          brightness: Brightness.light,
          fontFamily: UIData.vazirFont,
          primaryColor: Color(int.parse(_userAppConfig.primarycolor)),
          accentColor: Color(int.parse(_userAppConfig.accentcolor)),
        );
      } else {
        myTheme = ThemeData(
          brightness: Brightness.light,
          fontFamily: UIData.vazirFont,
          primaryColor: Colors.purple,
          accentColor: Colors.purple,
        );
      }
    });

    runApp(new MyApp(
      myTheme: myTheme,
    ));
  });

                                                     and use it here: 

class MyApp extends StatelessWidget {
  final ThemeData myTheme;

  MyApp({
    Key key,
    this.myTheme,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider<AppCustomers>(
          create: (_) {
            return AppCustomers();
          },
        ),
    ],
      child: ThemeProvider(
        initTheme: myTheme,
        child: Builder(
          builder: (context) {
            return MaterialApp(
              title: F.companyInfo.appCompanyName,
              theme: ThemeProvider.of(context),
              initialRoute: "/",
              routes: {
                "/": (context) => Helper.prepareScreen(SplashScreen()),
                UIData.receptionPointRoute: (context) =>
                    Helper.prepareScreen(ReceptionPointPage()),
              },
              debugShowCheckedModeBanner: false,
            );
          },
        ),
      ),
    );
  }
}
