### ISSUE TITLE
Icon moon to sun and back theme switcher

### ISSUE THREAD

**Issue by chitgoks** [kherel/animated_theme_switcher#33]
Possible to have like in the example sidebar where the icon changes from moon to sun?

**Comment by hnrq** [comment]
```dart
Icon(ThemeProvider.of(context)?.brightness == Brightness.light ? Icons.dark_mode_outlined : Icons.dark_mode);
```
Then you replace for the Icons you want. At least that's how I did

**Comment by chitgoks** [comment]
yes sorry. forgot to close. i did it like that
