### ISSUE TITLE
Crash on change theme

### ISSUE THREAD

**Issue by vishwajit76** [kherel/animated_theme_switcher#37]
When i change the theme ThemeSwitcher.

I/flutter ( 6544): When the exception was thrown, this was the stack:
I/flutter ( 6544): #0      ThemeSwitcherBoxClipper.getClip (package:animated_theme_switcher/src/clippers/theme_switcher_box_clipper.dart:14:25)
I/flutter ( 6544): #1      ThemeSwitcherClipperBridge.getClip (package:animated_theme_switcher/src/clippers/theme_switcher_clipper_bridge.dart:14:21)
I/flutter ( 6544): #2      _RenderCustomClip._updateClip (package:flutter/src/rendering/proxy_box.dart:1375:25)
I/flutter ( 6544): #3      RenderClipPath.paint (package:flutter/src/rendering/proxy_box.dart:1689:7)
I/flutter ( 6544): #4      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
I/flutter ( 6544): #5      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
I/flutter ( 6544): #6      RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2795:15)
I/flutter ( 6544): #7      RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629:5)
I/flutter ( 6544): #8      RenderStack.paint (package:flutter/src/rendering/stack.dart:645:7)
I/flutter ( 6544): #9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
I/flutter ( 6544): #10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
I/flutter ( 6544): #11     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
I/flutter ( 6544): #12     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:551:11)
I/flutter ( 6544): #13     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
I/flutter ( 6544): #14     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
I/flutter ( 6544): #15     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
I/flutter ( 6544): #16     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:394:12)
I/flutter ( 6544): #17     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1922:15)
I/flutter ( 6544): #18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
I/flutter ( 6544): #19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
I/flutter ( 6544): #20     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
I/flutter ( 6544): #21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
I/flutter ( 6544): #22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
I/flutter ( 6544): #23     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
I/flutter ( 6544): #24     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
I/flutter ( 6544): #25     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:139:11)
I/flutter ( 6544): #26     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
I/flutter ( 6544): #27     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:204:7)
I/flutter ( 6544): #28     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:185:7)
I/flutter ( 6544): #29     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
I/flutter ( 6544): #30     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
I/flutter ( 6544): #31     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
I/flutter ( 6544): #32     RenderAnimatedOpacityMixin.paint (package:flutter/src/rendering/proxy_box.dart:1016:17)
I/flutter ( 6544): #33     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
I/flutter ( 6544): #34     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
I/flutter ( 6544): #35     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
I/flutter ( 6544): #36     RenderFractionalTranslation.paint (package:flutter/src/rendering/proxy_box.dart:2723:13)
I/flutter ( 6544): #37     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
I/flutter ( 6544): #38     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
I/flutter ( 6544): #39     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
I/flutter ( 6544): #40     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
I/flutter ( 6544): #41     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:139:11)
I/flutter ( 6544): #42     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
I/flutter ( 6544): #43     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:204:7)
I/flutter ( 6544): #44     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:185:7)
I/flutter ( 6544): #45     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
I/flutter ( 6544): #46     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
I/flutter ( 6544): #47     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
I/flutter ( 6544): #48     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
I/flutter ( 6544): #49     RenderOffstage.paint (package:flutter/src/rendering/proxy_box.dart:3383:11)
I/flutter ( 6544): #50     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
I/flutter ( 6544): #51     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
I/flutter ( 6544): #52     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
I/flutter ( 6544): #53     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
I/flutter ( 6544): #54     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
I/flutter ( 6544): #55     _RenderTheatre.paintStack (package:flutter/src/widgets/overlay.dart:780:15)
I/flutter ( 6544): #56     _RenderTheatre.paint (package:flutter/src/widgets/overlay.dart:798:7)
I/flutter ( 6544): #57     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
I/flutter ( 6544): #58     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
I/flutter ( 6544): #59     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
I/flutter ( 6544): #60     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
I/flutter ( 6544): #61     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
I/flutter ( 6544): #62     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
I/flutter ( 6544): #63     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
I/flutter ( 6544): #64     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
I/flutter ( 6544): #65     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
I/flutter ( 6544): #66     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
I/flutter ( 6544): #67     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
I/flutter ( 6544): #68     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
I/flutter ( 6544): #69     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
I/flutter ( 6544): #70     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
I/flutter ( 6544): #71     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
I/flutter ( 6544): #72     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
I/flutter ( 6544): #73     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
I/flutter ( 6544): #74     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
I/flutter ( 6544): #75     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
I/flutter ( 6544): #76     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)
I/flutter ( 6544): #77     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)
I/flutter ( 6544): #78     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
I/flutter ( 6544): #79     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:139:11)
I/flutter ( 6544): #80     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
I/flutter ( 6544): #81     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:204:7)
I/flutter ( 6544): #82     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:185:7)
I/flutter ( 6544): #83     RenderView.paint (package:flutter/src/rendering/view.dart:200:15)
I/flutter ( 6544): #84     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)
I/flutter ( 6544): #85     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:139:11)
I/flutter ( 6544): #86     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
I/flutter ( 6544): #87     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:975:29)
I/flutter ( 6544): #88     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:464:19)
I/flutter ( 6544): #89     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:876:13)
I/flutter ( 6544): #90     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:328:5)
I/flutter ( 6544): #91     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
I/flutter ( 6544): #92     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
I/flutter ( 6544): #93     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:998:5)
I/flutter ( 6544): #97     _invoke (dart:ui/hooks.dart:163:10)
I/flutter ( 6544): #98     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:259:5)
I/flutter ( 6544): #99     _drawFrame (dart:ui/hooks.dart:126:31)
I/flutter ( 6544): (elided 3 frames from dart:async)

**Comment by kherel** [comment]
Closing this issue after a prolonged period of inactivity.
