### ISSUE TITLE
System controlled dark mode not working when using ThemeSwitchingArea

### ISSUE THREAD

**Issue by EngFoggy** [kherel/animated_theme_switcher#40]
The system controlled dark mode doesn't work when using a ThemeSwitchingArea. I can use the plugin without the circle/box animation, but the effect is not the same.
I also tried playing with the MaterialApp themeMode parameter, but when there's a ThemeSwitchingArea, it seems that it considers only the light theme..

Maybe adding the darkTheme to ThemeSwitcher.of(context)!.changeTheme() could solve the issue. I really like your plugin, but I don't want to give up on system managed light/dark mode.

**Comment by kherel** [comment]
Please provide minimum code example that reliably demonstrates the issue.

**Comment by kherel** [comment]
Sorry for the big delay in response...
