### ISSUE TITLE
When closing the application, the theme is not saved

### ISSUE THREAD

**Issue by Kerabor** [kherel/animated_theme_switcher#41]
What should I prescribe so that the theme is saved when exiting the application?

**Comment by EngFoggy** [comment]
Honestly I don't think this package is actually in charge of doing that.
You can use SharedPreferences to save a variable that lets you identify the applied theme, and read it before initializing ThemeProvider.

**Comment by Kerabor** [comment]
> Честно говоря, я не думаю, что этот пакет действительно отвечает за это. Вы можете использовать SharedPreferences для сохранения переменной, которая позволяет идентифицировать примененную тему и читать ее перед инициализацией ThemeProvider.

I tried it. I can't ... the application does not start stupidly

**Comment by kherel** [comment]
> What should I prescribe so that the theme is saved when exiting the application?

The package is only responsible for animation, and does not imply saving current theme. But check the extra example...
