### ISSUE TITLE
It is not clear where to pass colors for each element!

### ISSUE THREAD

**Issue by Kerabor** [kherel/animated_theme_switcher#42]
It's not at all clear how to change colors !!!
The theme_config.dart only has values ​​for Checkbox ... for dark and light mode there are no parameters and cannot be added!
![image](https://user-images.githubusercontent.com/74487698/140460837-b5e6249e-6ce0-4041-9896-29c1412ee3b7.png)

And I can't figure out where to insert so that the top status bar is transparent!

> appBarTheme: AppBarTheme(
        systemOverlayStyle: SystemUiOverlayStyle(
        statusBarIconBrightness: Brightness.dark,
        statusBarColor: Colors.transparent, ),
[
![image](https://user-images.githubusercontent.com/74487698/140461016-af89602a-c90c-4e04-bceb-72b6723b0e12.png)
](url)

**Comment by EngFoggy** [comment]
ThemeData is not defined in this package, but is part of Flutter.
[https://api.flutter.dev/flutter/material/ThemeData-class.html](https://api.flutter.dev/flutter/material/ThemeData-class.html)

**Comment by Kerabor** [comment]
> ThemeData не определена в этом пакете, но является частью Flutter. https://api.flutter.dev/flutter/material/ThemeData-class.html

And what does it mean? For example, I have Carsel and BoxShadow, so how can I change this color in the black theme? Color Shadow applies only to buttons ...........

**Comment by kherel** [comment]
The question you've linked to is not related to the library. Please refrain from opening issues which do not pertain to the library, thanks!
