### ISSUE TITLE
After upgrading to 2.0.3, there is now an error in the code

### ISSUE THREAD

**Issue by Kerabor** [kherel/animated_theme_switcher#44]
After upgrading to 2.0.3, there is now an error in the code, OnPressed(((

![Безымянный](https://user-images.githubusercontent.com/74487698/143732644-b75197ab-6799-4b76-853a-9bd4eb971157.png)

**Comment by kherel** [comment]
I've changed the variable name now it's called isReversed, and to get previous theme you need to call ThemeModelInheritedNotifier.of(context).theme
