### ISSUE TITLE
Bug once theme switcher is actived and showModalBottomSheet is used

### ISSUE THREAD

**Issue by chitgoks** [kherel/animated_theme_switcher#46]
I have a listview, and a theme switcher in the appbar.

when the switch is done, changing the theme, and i call showModalBottomSheet(), it also somehow includes the first item of the listview

see image.

not sure if it's the prob of this lib or flutter. it worked before.

my content is also a stack widget.

```
showModalBottomSheet(
                  context: context,
                  clipBehavior: Clip.antiAliasWithSaveLayer,
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.vertical(top: Radius.circular(10.0))),
                  builder: (context) => Wrap(
                    children: [
                      _getRemoveAdsBox(),
                    ],
                  );
```

![ss](https://user-images.githubusercontent.com/3955470/145705053-8f0abcfb-a116-42ee-9adb-5d82318dbd0a.png)

**Comment by kherel** [comment]
HI @chitgoks, add a minimal code example, I'll try to help you.

**Comment by chitgoks** [comment]
hi ill close this. i removed ThemeSwitchingArea for the widget in bottomsheet. and did an if else for text color
