### ISSUE TITLE
screenshot image is blurry

### ISSUE THREAD

**Issue by Mehrdad-Davoudi** [kherel/animated_theme_switcher#6]
when switching theme screen shot is blurry.
set pixelRatio to 2.0 fixing it.
`  Future<void> _saveScreenshot() async {
    RenderRepaintBoundary boundary = _previewContainer.currentContext.findRenderObject();
    image = await boundary.toImage(pixelRatio: 2.0);
  }`

**Comment by Viper-Bit** [comment]
thx nice job, added in my pr.

**Comment by kherel** [comment]
thanks to everybody. the package has been updated.
